language: generic
script: false

stages:
  - name: Jorts
    if: type = cron OR (commit_message =~ /jortleby/) OR (tag IS present AND tag =~ /^hello/)
  - Jants
  - okay

jortle: tortle

jobs:
  include:
    - stage: Jorts
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: okay
      script: /bin/false

notifications:
  slack:
    on_success: change
    on_failure: change
    on_error: change
    rooms:
      secure: FmzIVU1ykaTFfo6HLD1+QCBrWsyulgieuuymlXPj1okddOzpY6XOlqadzZWYrzXdWxv3GLsRs0tXOYXwZ3Q/816RlJXIQKxaLf0qgx20uVecesI0iaETZW6AOqK1hr4U6AYaSO5Z5uV3OMvQJJxlEKSx0nkR5O+nGVZDT26QHC46ugtQ0gUZ1Ep+vAM3by4x1rx50fXU6JSUHmU8MtW1hzZWkd0eSZn/knG0mrI2ajsnCt42mMj4AdTp204ze+wOKPsTBhMyvuGp8s6PQVAphWj4zwCe6xuGl0Di5cFPykaUSGsA0PALilgdwL6pbv8v3K8pazIqFWHcBx1psg7HoXwdthZhxO8ROULPmqqzqSijetefc4oqZDfhZSrOLuv2ESYuVpkskpP6R1kdACFtouEZQYPwyFxJRnp1hGLO0sLsBEq9awCwHYTX0fpD6GaaWH/bHgrK9dA2o1VeyskVMclgGTwzFbQQjxDiXVTNleD5X7QWFK07RoOJOJ0ahNzl+il7FIXqQsS1k47xmK27hVKelwWstS+SqbxcJKCKzJFfVLQMWn0TUbJdt9SuLqB3y1fBYiRiXH43XvthjnzZGLZhmCeCrlN59326Tv1pU461gqtVYu997r1LZBjBjHHReI/A0hhvIBMNK/IUkM3kyUG+J8Z9YvpbkJO2JJURKjQ=
