language: ruby
rvm:
  - "2.3.3"
sudo: false
before_install:
  - rvm get stable --auto-dotfiles
  - gem install bundler
  - nvm list
  - echo "ğŸ™ƒ"
  - "echo 'ğŸ˜†ğŸ˜­ğŸ›ğŸ™ƒğŸ¤”ğŸ¤— :bug: :tada:'"
  - "./echo-emoji.sh"
script:
  - rvm -v
  - rvm alias list
  - ruby -v
  - rvm list
  - ruby test.rb
notifications:
  email: false
